"""Agregar campos rol, turno y sucursal_id a usuarios

Revision ID: 37b48f4b7af7
Revises: 
Create Date: 2025-11-27 15:41:26.491032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37b48f4b7af7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortes_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_inicial', sa.Float(), nullable=True),
    sa.Column('monto_final', sa.Float(), nullable=True),
    sa.Column('total_ventas', sa.Float(), nullable=True),
    sa.Column('total_cancelaciones', sa.Float(), nullable=True),
    sa.Column('total_efectivo', sa.Float(), nullable=True),
    sa.Column('total_tarjeta', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklists_salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('limpieza_correcta', sa.Boolean(), nullable=True),
    sa.Column('danos_habitacion', sa.Boolean(), nullable=True),
    sa.Column('objetos_olvidados', sa.Boolean(), nullable=True),
    sa.Column('muebles_danados', sa.Boolean(), nullable=True),
    sa.Column('equipo_danado', sa.Boolean(), nullable=True),
    sa.Column('cargo_danos', sa.Float(), nullable=True),
    sa.Column('cargo_limpieza', sa.Float(), nullable=True),
    sa.Column('otros_cargos', sa.Float(), nullable=True),
    sa.Column('observaciones_danos', sa.Text(), nullable=True),
    sa.Column('observaciones_generales', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['renta_id'], ['rentas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reservas')
    with op.batch_alter_table('habitaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=False))
        batch_op.alter_column('precio_base',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'150'"))
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])

    with op.batch_alter_table('rentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('motivo_cancelacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monto_devolucion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cancelada_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['cancelada_por'], ['id'])
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])
        batch_op.drop_column('reserva_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sucursal_id')
        batch_op.drop_column('turno')
        batch_op.drop_column('rol')

    with op.batch_alter_table('rentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cancelada_por')
        batch_op.drop_column('monto_devolucion')
        batch_op.drop_column('motivo_cancelacion')
        batch_op.drop_column('sucursal_id')

    with op.batch_alter_table('habitaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('precio_base',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'150'"))
        batch_op.drop_column('sucursal_id')

    op.create_table('reservas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('habitacion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recepcionista_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cliente_telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_reserva', sa.DATE(), nullable=False),
    sa.Column('hora_reserva', mysql.TIME(), nullable=False),
    sa.Column('horas_reservadas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=20), server_default=sa.text("'PENDIENTE'"), nullable=True),
    sa.Column('precio_estimado', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('confirmada_at', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_hora_entrada_real', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_hora_salida_real', mysql.DATETIME(), nullable=True),
    sa.Column('horas_extras', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('pago_final', mysql.FLOAT(), nullable=True),
    sa.Column('tipo_ingreso', mysql.ENUM('vehiculo', 'a_pie'), server_default=sa.text("'vehiculo'"), nullable=True),
    sa.Column('placa_vehiculo', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['habitacion_id'], ['habitaciones.id'], name=op.f('reservas_ibfk_1')),
    sa.ForeignKeyConstraint(['recepcionista_id'], ['users.id'], name=op.f('reservas_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('checklists_salida')
    op.drop_table('cortes_caja')
    # ### end Alembic commands ###
